### ISSUE TITLE
map crashed when clicking delete button

### ISSUE THREAD

**Issue by florenso** [HU-R2D2/mapeditor#11]
steps to recreate bug
1. Open map editor
2. Load a map
3. Click on delete button
4. Click on a tile in the map (left mouse button)
5. Click on the delete button again

(instead of step 3 using the shortcut ctrl+A will also cause the progam to crash)

![image](https://cloud.githubusercontent.com/assets/9743844/15229767/ca6afefc-1892-11e6-8c27-b3128a41451b.png)

**Comment by florenso** [comment]
same bug with Set button

**Comment by Yoyasp** [comment]
Fixed by my new code.. delete and set both work
