### ISSUE TITLE
edits extra row of tiles below selected tiles

### ISSUE THREAD

**Issue by florenso** [HU-R2D2/mapeditor#14]
this could be a map related problem...
bug could also be system related (floating point rounding might differ per system)

![image](https://cloud.githubusercontent.com/assets/9743844/15230239/f2c3846c-1894-11e6-8507-fdb3ad142ddd.png)
![image](https://cloud.githubusercontent.com/assets/9743844/15230251/045221b6-1895-11e6-8939-20f8c3140c2c.png)

**Comment by Yoyasp** [comment]
Fixed, now it does it pixelperfect (or better i dont really know :/ )
