### ISSUE TITLE
crash when canceling save(as)

### ISSUE THREAD

**Issue by florenso** [HU-R2D2/mapeditor#15]
![image](https://cloud.githubusercontent.com/assets/9743844/15231798/8a910e60-189d-11e6-906c-d908cfe3cef0.png)
![image](https://cloud.githubusercontent.com/assets/9743844/15231808/9fcfe4f4-189d-11e6-881e-acc80a86978d.png)

**Comment by JopvBuuren** [comment]
Niet reproduceer baar
